### ISSUE TITLE
Extend to be usable for general repos

### ISSUE THREAD

**Issue by hianhianhian** [godotengine/godot-interactive-changelog#1]
Hey, I came across this tool and I think it's a really great tool. I was wondering if it could be extended to be easily used for other repos? I can see this being useful for many other projects.

**Comment by YuriSizov** [comment]
@hianhianhian It's already possible to use it with any repository. It defaults to fetching from `godotengine/godot`, but you can change that with CLI arguments. The README explains how to add a new configuration and how to use CLI arguments.

You may want to modify the template and either change `/src/shared/components/SharedNavigation.js` or remove it from `entry.js`, since it has a navigation component for other Godot pages.

**Comment by hianhianhian** [comment]
Ah okay thanks for the info, that's really cool! I'll close this issue then

**Comment by YuriSizov** [comment]
Ah, one more thing. There is a bit of Godot-specific processing going on with labels to generate the release notes view in https://github.com/godotengine/godot-interactive-changelog/blob/master/src/paths/index/components/changes/ReleaseNotesItem.js

So that's also something you may want to modify. I can try to move this stuff to a more obvious location so you don't have to go deep into files to remove it from your fork, if you want.

**Comment by hianhianhian** [comment]
Ah okay good to know

Btw there's also this little bit here that defaults to `godotengine/godot` but it's trivial to modify that
https://github.com/godotengine/godot-interactive-changelog/blob/75ae068fc0db48ee397ab7985140e3427dd35d26/src/paths/index/entry.js#L50

**Comment by YuriSizov** [comment]
Ah, good catch! In this repo I never override this value indeed.
